services:
  php:
    build: .
    container_name: app
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:11.6
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: php
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 1s
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  db_data:

